[version] Updated to DCEVM 8u112
anapsix/docker-alpine-java pull request #31
Opened 2017-01-17 21:21 UTC by albundy83

2017-01-19 21:08 UTC, anapsix requested changes
do you mind mentioning the DCEVM version in README.md :)

2017-01-19 21:20 UTC, albundy83 commented
I think I'm good now ?

2017-01-20 14:45 UTC, anapsix approved these changes

2017-01-20 14:46 UTC, albundy83 commented
Yeaaahhh 😊

2017-01-20 14:48 UTC, merged