[version] 8u121 b13
anapsix/docker-alpine-java pull request #32
Opened 2017-01-19 20:38 UTC by albundy83

Hello,
just a demo on how I have fixed the new url link of oracle.
Tell me what you think.

2017-01-19 21:18 UTC, anapsix requested changes
that should work, however please update README.md to reflect latest version of Java and DCEVM

2017-01-19 21:18 UTC, anapsix commented on generate_dockerfiles.sh
> +  if [ "${JVM_MINOR}" -ge 121 ]; then
I see what you are doing.. cause they need to be difficult now..

2017-01-19 21:25 UTC, albundy83 commented on generate_dockerfiles.sh
> +  if [ "${JVM_MINOR}" -ge 121 ]; then
Yes not sure if it's very clean but it's not too ugly.

2017-01-20 15:06 UTC, merged

2017-01-20 15:19 UTC, anapsix commented
thanks @albundy83!